### ISSUE TITLE
How do I edit the CSS? [Params] doesn't seem to work

### ISSUE THREAD

**Issue by valzi** [avianto/hugo-kiera#13]
I tried

```
[params.assets]
customCSS = ["css/custom.css"]
```

and
```

[params]
customCSS = ["css/custom.css"]
```

but neither seems to work. What is the best way to do this in Kiera?

**Comment by bkanuka** [comment]
After merging the above PR, you should be able to use

```
  [params]
    customCSS = ["css/custom.css"]
```

**Comment by RamanBut-Husaim** [comment]
@valzi @bkanuka 

It seems that the working section at the moment looks something like this for yml:

```yml
params:
  assets:
    customCSS:
      - "css/custom.css"
```
